# Generated by Django 3.2.2 on 2021-05-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary6',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='diary6',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
